[package]
name = "rush"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rush"
path = "src/rush.rs"

[dependencies]
nom = "7"
glob = "0.3"
crossterm = "0.26"
home = "0.5"
log = "0.4"
log4rs = "1"
dyn-clone = "1"
chrono = "0.4"